Process rst files to add reference link destinations. Added underbar prefix to pdf copy statement.

diff --git a/doc/doc b/doc/doc
--- a/doc/doc
+++ b/doc/doc
@@ -8,11 +8,10 @@ function main() {
     # debug: function main
     # debug: $1 = Modified Arguments
 
-    Python_directory="trustedanalytics"
+    PythonDirectory="trustedanalytics"
     JavaCall="java.*launcher/target/launcher.jar.*org.trustedanalytics.atk.component.Boot"
-
-    echo
-
+    PDFName="Documentation"
+    UnderbarFolderPrefix="f"
     ModifiedArguments=$1
     ScriptPath=$(dirname "$(readlink -f "$0")")
     LogFile=$ScriptPath/doc.log; if [ -e $LogFile ]; then rm $LogFile; fi
@@ -31,7 +30,7 @@ function main() {
 
     # debug: Check on quiet mode
     echo $ModifiedArguments | grep -i -e "/-q/" -e "/-qq/" > /dev/null
-    if [ $? == 0 ]; then
+    if [ "$?" == "0" ]; then
         AskThem=No
     else
         AskThem=Yes
@@ -39,7 +38,7 @@ function main() {
 
     # debug: Check on super quiet mode
     echo $ModifiedArguments | grep -i -e "/-qq/" > /dev/null
-    if [ $? == 0 ]; then
+    if [ "$?" == "0" ]; then
          DisplayStatus=No
     else
          DisplayStatus=Yes
@@ -47,7 +46,7 @@ function main() {
 
     # debug: Look for help
     echo $ModifiedArguments | grep -i -e "/-h/" -e "/--help/" > /dev/null
-    if [ $? == 0 ]; then
+    if [ "$?" == "0" ]; then
         doc_help $ModifiedArguments
         return 0
     fi
@@ -107,7 +106,7 @@ function main() {
         # debug: Update the additional python documentation files
         echo $ModifiedArguments | grep -i "/-p/" > /dev/null
         if [ "$?" == "1" ]; then
-            pushd ../python-client/$Python_directory/doc > /dev/null
+            pushd ../python-client/$PythonDirectory/doc > /dev/null
             build_docstubs $AskThem $DisplayStatus $TempFile $LogFile
             Return=$?
             popd > /dev/null
@@ -115,8 +114,11 @@ function main() {
         fi
 
         # debug: Add references at the beginning of all rst files
-        add_reference $AskThem $DisplayStatus $TempFile $LogFile
-        if [ "$?" != "0" ]; then return 1; fi
+        echo $ModifiedArguments | grep -i "/-r/" > /dev/null
+        if [ "$?" == "1" ]; then
+            add_reference $AskThem $DisplayStatus $TempFile $LogFile
+            if [ "$?" != "0" ]; then return 1; fi
+        fi
 
         RunCommand="which sphinx-build"
         do_this "$RunCommand" $AskThem "No" $TempFile $LogFile
@@ -151,11 +153,11 @@ function main() {
             RunCommand="which pdflatex"
             do_this "$RunCommand" $AskThem "No" $TempFile $LogFile
             if [ "$?" != "0" ]; then return 1; fi
-            pdf_build latex Package_Documentation $AskThem $DisplayStatus $TempFile $LogFile
+            pdf_build latex "$PDFName" $AskThem $DisplayStatus $TempFile $LogFile
             if [ "$?" != "0" ]; then return 1; fi
-            if [[ -f build/latex/Package_Documentation.pdf && -d build/html/_downloads ]]; then
-                if [ -s build/latex/Package_Documentation.pdf ]; then
-                    RunCommand="cp build/latex/Package_Documentation.pdf build/html/_downloads/"
+            if [[ -f "build/latex/"$PDFName".pdf" && -d "build/html/"$UnderbarFolderPrefix"_downloads" ]]; then
+                if [ -s build/latex/"$PDFName".pdf ]; then
+                    RunCommand="cp build/latex/"$PDFName".pdf build/html/"$UnderbarFolderPrefix"_downloads/"
                     do_this "$RunCommand" $AskThem $DisplayStatus $TempFile $LogFile
                     if [ "$?" != "0" ]; then return 1; fi
                 else
@@ -170,7 +172,7 @@ function main() {
 
     # debug: Test the examples
     echo $ModifiedArguments | grep -i -e "/test/" > /dev/null
-    if [ $? == 0 ]; then
+    if [ "$?" == "0" ]; then
         for File in $(ls -1a source/*.rst)
         do
             echo $File
@@ -179,16 +181,16 @@ function main() {
 
     # debug: Compress the results into a single file
     echo $ModifiedArguments | grep -i -e "/zip/" > /dev/null
-    if [ $? == 0 ]; then
+    if [ "$?" == "0" ]; then
         RunCommand="which zip"
         do_this "$RunCommand" $AskThem "No" $TempFile $LogFile
-        if [ "$?" == "0" ]; then
-            if [[ -e documentation.zip ]]; then
-                rm documentation.zip
-            fi
-            RunCommand="zip -q -9 -r documentation build/html"
-            do_this "$RunCommand" $AskThem $DisplayStatus $TempFile $LogFile
+        if [ "$?" != "0" ]; then return 1; fi
+        if [[ -e documentation.zip ]]; then
+            rm documentation.zip
         fi
+        RunCommand="zip -q -9 -r documentation build/html"
+        do_this "$RunCommand" $AskThem $DisplayStatus $TempFile $LogFile
+        if [ "$?" != "0" ]; then return 1; fi
     fi
     # debug: Delete doc file
     if [ -e doc.log ]; then
@@ -216,23 +218,31 @@ function add_reference() {
     else
         rm $3 > /dev/null
     fi
-    RandomFileName="$(date +%N).tmp"
+    RandomFileName="$(date +%Y%m%d%H%M%N).tmp"
     for File in $RSTFiles; do
-        Line=".. _$File:"
+        Line=".. _${File:7}:"
         # debug: Check for the reference already existing
         grep "$Line" "$File" > /dev/null
         if [ "$?" != "0" ]; then
             # debug: Reference does not exist in the existing file
             RunCommand="cp $File $RandomFileName"
-            do_this "$RunCommand" $1 $2 $3 $4
+            do_this "$RunCommand" $1 "No" $3 $4
             Return=$?
             if [ "$Return" != "0" ]; then return $Return; fi
-            log_step "awk 'BEGIN {print '\"$Line\"'} {print $0}' $RandomFileName > $File" $2 $4
-            awk 'BEGIN {print "'"$Line"'"} {print $0}' $RandomFileName > $File
-            return 1
+            # debug: Add the line to the beginning of the file
+            echo "awk 'BEGIN {print \"'\"$Line\"'\"; print \"\"} {print $0}' $RandomFileName > $File" >> $3
+            awk 'BEGIN {print "'"$Line"'"; print ""} {print $0}' $RandomFileName > $File
+            if [ "$?" != "0" ]; then
+                Err "awk" $1 $2 $3 $4
+                Return=$?
+                if [ "$Return" != "0" ]; then return $Return; fi
+            fi
         fi
     done
-    return 1
+    if [ -f "$RandomFileName" ]; then
+        rm "$RandomFileName"
+    fi
+    return 0
 }
 
 #############################################################################################################
@@ -350,9 +360,10 @@ function doc_help() {
     echo "+e:         Erase doctrees"
     echo "-p:         Do not rebuild docstub files"
     echo "-q, -qq:    Quiet mode, use default values for prompts"
+    echo "-r:         Do not add reference labels to files (this will cause some links to fail)"
     echo "-s:         Do not compile Scala code"
     echo "+t:         Use threads during maven compilations"
-    echo "-_:         Do not rename html folders starting with _ to f_"
+    echo "-_:         Do not rename html folders starting with _ to "$UnderbarFolderPrefix"_"
     echo
     echo "dirhtml:    Compile to html segregated with directories"
     echo "html:       Compile to html"
@@ -446,7 +457,6 @@ function log_step() {
         echo "$1"
     fi
     echo >> $3
-    echo >> $3
     echo "$1" >> $3
     return 0
 }
@@ -487,7 +497,7 @@ function packages() {
     # Yes for "packages", check for permissions
     if [ -f $2/$TECHWRITERS ]; then
         echo $1 | grep -f $2/$TECHWRITERS > /dev/null
-        if [ $? == 0 ]; then
+        if [ "$?" == "0" ]; then
             echo Checking the installed packages.
             # The packages need superuser rights to install properly.
             sudo -E $2/install_packages.sh
@@ -558,7 +568,6 @@ function rename_folders() {
     # debug: rename_folders
 
     BuildDirectory="$ScriptPath/build/$1"
-    Prefix="f"
     pushd $BuildDirectory > /dev/null
     LongNames=$(find -name "_*"|sort -r)
     echo $LongNames=LongNames
@@ -578,11 +587,11 @@ function rename_folders() {
         echo $ChangeFiles=ChangeFiles
         for ChangeFile in $ChangeFiles; do
             mv $ChangeFile $WorkingFile
-            sed "s/$Name/$Prefix\0/g" < $WorkingFile > $ChangeFile
+            sed "s/$Name/$UnderbarFolderPrefix\0/g" < $WorkingFile > $ChangeFile
         done
     done
     for Name in $LongNames; do
-        mv $Name $(echo "$(dirname $Name)/$Prefix$(basename $Name)")
+        mv $Name $(echo "$(dirname $Name)/$UnderbarFolderPrefix$(basename $Name)")
     done
     if [[ -e "$WorkingFile" ]]; then
         rm $WorkingFile
@@ -632,7 +641,7 @@ function server_start() {
         pushd ../ > /dev/null
         echo -n "Start server"
         RunCommand="Start server (nohup bin/rest-server.sh)"
-        log_step "$RunCommand" "No" $4
+        log_step "$RunCommand" $1 "No" $3 $4
         nohup bin/rest-server.sh < /dev/null > $3 2>&1 &
         Return=$?
         popd > /dev/null
@@ -679,7 +688,7 @@ function server_stop() {
     while [ "$Looping" == "0" ]; do
         echo -n "Stop server $ProcessID"
         kill $ProcessID
-        if [ $? != 0 ]; then
+        if [ "$?" != "0" ]; then
             echo
             Err "Stop server $ProcessID" $1 $2 $3 $4
             Return=$?
